CREATE TABLE IF NOT EXISTS hackernews(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT,
    text TEXT,
    embedding vector(384),
    chunk_start BIGINT NOT NULL,
    chunk_end BIGINT NOT NULL,
    chunk_no INT,
    type TEXT NOT NULL check (type IN ('story', 'comment')),
    author TEXT,
    time TIMESTAMPTZ NOT NULL,
    title TEXT,
    score INT,
    dead BOOLEAN,
    deleted BOOLEAN,

    CONSTRAINT unique_chunk  UNIQUE(doc_id, chunk_no)
)
