CREATE TABLE IF NOT EXISTS hackernews(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id BIGINT NOT NULL,
    title TEXT,
    author TEXT,
    text TEXT NOT NULL,
    time TIMESTAMPTZ NOT NULL,
    type TEXT NOT NULL check (type IN ('story', 'comment')),
    score INT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL,
    dead BOOLEAN NOT NULL,
    embedding vector(384) NOT NULL,
    chunk_no INT NOT NULL,
    chunk_start BIGINT NOT NULL,
    chunk_end BIGINT NOT NULL,

    CONSTRAINT unique_chunk  UNIQUE(doc_id, chunk_no)
)
